(define (problem planety_prob)
    (:domain planety) 
(:objects unit1 - equipment)
(:init

    (at 0 (not (commsOpen)))
    (available unit1)
    (= A_rate 4.0)
    (= B_rate 2.0)
    (= C_rate 2.5)
    (= D_rate 1.5)
    (= obs1_rate 4)
    (= obs2_rate 5)
    (= fullprepare_durtime 3)
    (= observe1_durtime 7)
    (= observe2_durtime 8)
    (= prepareobs1_durtime 1)
    (= prepareobs2_durtime 2)
    (= demand 0)
    (= supply 0)
    (= soc 93)
    (= charge_rate 0.0095)
    (= daytime 4)
    (= heater_rate 15.1)
    (= dusk 9.0)
    (= dawn 3.0)
    (= safeLevel 15.0)
    (= solar_const 0.03)
    (not(gotObs1 ))
    (not(gotObs2 ))
    (not(readyforobs1))
    (not(readyforobs2 ))
    (day)
     )
     (:goal (and (gotObs1) (gotObs2)))
    
) 

