(define (problem run-generator2)
(:domain generator)
(:objects generator - gen tank1 tank2 tank3 tank4 tank5 tank6 tank7 tank8 tank9 tank10 - tank )
(:init
(= ( gen_fuel_level generator) 860)
(= ( capacity generator) 1000)
(= ( tank_fuel_level tank1 ) 16)
(= ( sqrtvolinit tank1 ) 4)
(= ( flow_constant tank1 ) 0.1)
(= ( tank_fuel_level tank2 ) 16)
(= ( sqrtvolinit tank2 ) 4)
(= ( flow_constant tank2 ) 0.1)
(= ( tank_fuel_level tank3 ) 16)
(= ( sqrtvolinit tank3 ) 4)
(= ( flow_constant tank3 ) 0.1)
(= ( tank_fuel_level tank4 ) 16)
(= ( sqrtvolinit tank4 ) 4)
(= ( flow_constant tank4 ) 0.1)
(= ( tank_fuel_level tank5 ) 16)
(= ( sqrtvolinit tank5 ) 4)
(= ( flow_constant tank5 ) 0.1)
(= ( tank_fuel_level tank6 ) 16)
(= ( sqrtvolinit tank6 ) 4)
(= ( flow_constant tank6 ) 0.1)
(= ( tank_fuel_level tank7 ) 16)
(= ( sqrtvolinit tank7 ) 4)
(= ( flow_constant tank7 ) 0.1)
(= ( tank_fuel_level tank8 ) 16)
(= ( sqrtvolinit tank8 ) 4)
(= ( flow_constant tank8 ) 0.1)
(= ( tank_fuel_level tank9 ) 16)
(= ( sqrtvolinit tank9 ) 4)
(= ( flow_constant tank9 ) 0.1)
(= ( tank_fuel_level tank10 ) 2)
(= ( sqrtvolinit tank10 ) 4)
(= ( flow_constant tank10 ) 0.1)
(= (runtime) 1000))
(:goal (generator_ran generator))
(:metric minimize ( total-time ))
)
